### PR TITLE
🧪🚇 Add integration test result validation (maintain/0.4.1)

### PR DESCRIPTION
**Pull request by s-weigand**
Right now the integration tests only show breaking API changes, but checking validity is still a manual task.
This PR adds a way to compare the results to a "gold standard" (tag, branch, commit) set by [this workflow](https://github.com/glotaran/pyglotaran-examples/actions/workflows/update_compare_results.yml) on the `pyglotaran-examples` repo.

### Change summary

- Adds numerical comparison to "gold standard" results defined by `pyglotaran-examples`

### Checklist

- [x] ✔️ Passing the tests (mandatory for all PR's)
- [x] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)

### CODE REVIEW

**Comment by s-weigand** [comment]
We (@jsnel and @s-weigand ) figured out which examples need to be reviewed (`EXAMPLE_BLOCKLIST`) and that the SVD (which is just used for tooling) gives different results on windows vs. linux and thus needs a less strict threshhold.

**Review by jsnel — APPROVED** [review]
LGTM. I think we have tested this enough.

There's still the residual matter of the results not being exactly the same depending on the environment it's run in (and sometimes even consecutive runs of the CI) but this is a different matter that can always be resolved on a per case basis by manual inspection if needed. The tolerances set now are now at least enough to not trigger to many false positives on the CI and at least catch true positives (as in some regression).

**Comment by jsnel** [comment]
Keeping this PR open as a sanity test for a similar PR to staging for the "Compare results" feature.

**Review by jsnel — APPROVED** [review]
👌

**Pull request merged**
