### PR TITLE
🩹 Fix schema generation by making private attributes private

### PR DESCRIPTION
**Pull request by s-weigand**
With pydantic 2 we had crashes when calling `.model_json_schema()` e.g.

```py
from glotaran.project import Scheme

Scheme.model_json_schema()
```

The main reason for this was pydatic failure to serialize `data_model_type` to json since the value is a class.

~~This can all be prevented by making internal only fields "private" (leading `_`) so they get excluded from the schema since we don't want users to put values for them anyway.~~

As @joernweissenborn  noted properly typing the fields with `ClassVar` those variables will also not be considered for the schema.

### CODE REVIEW

**Comment by s-weigand** [comment]
This PR is a draft since it depends on #1381

**Comment by jsnel** [comment]
> This PR is a draft since it depends on #1381

That PR has been merged, so promoting this PR.

**Review by jsnel — APPROVED** [review]
LGTM. Examples ran successfully.

**Review by joernweissenborn — APPROVED** [review]
Lgtm, but in the long run we should put these things into a `ElementConfig` class.

**Pull request merged**
