### PR TITLE
🩹 Add number_of_clps to result and correct degrees_of_freedom calculation

### LINKED ISSUE #1086: 🐛 small corrections of the Optimization result table
Currently, the degrees of freedom is calculated as
n_data - n_parameters 
and does not take into account the clp.

it may be that you already do the bookkeeping of the number of clp somewhere in the code.
then the following may partly be superfluous.

for a kinetic model (analogously for a spectral or spectrotemporal model)
for all wavelengths
after you have resolved all the constraints
store the number of clp at that wavelength (the number of columns of Ctilde) in vector nclparr

then nclptotal is the sum of all elements in nclparr 

The correct degrees of freedom should then be calculated as
n_data - n_parameters - nclptotal 
and nclptotal should be reported when you print the Optimization result table
(after line 190 in result.py)
["Number of conditionally linear parameters", self.number_of_clp]

### PR DESCRIPTION
**Pull request by s-weigand**
This change adds `number_of_clps` to the `MatrixProvider`'s, `OptimizationGroup` and the `Result` classes.
When degrees of freedom are calculated the `number_of_clps` are subtracted.

In addition `number_of_data_points` was deprecated from `Result` since we found that what we actually report is `number_of_residuals` which is the more interesting value anyway since it also contains the penalties.
So following a discussion @ism200 we won't report the number of datapoints anymore.

### Change summary

- [🗑️ Deprecated Result.number_of_data_points in favor of Result.number_of_residuals](https://github.com/glotaran/pyglotaran/commit/549dad60c68c0ee58760353a40f611b573669c43)
- [✨ Add number_of_clps property to MatrixProvider's and OptimizationGroup](https://github.com/glotaran/pyglotaran/commit/7efbd5c931605cecef22be5b594dda4875270504)
- [👌 Add number_of_clps to result and adjust degrees_of_freedom calculation](https://github.com/glotaran/pyglotaran/commit/5d1ce1384e3f318be4392a84e22bf2a878d098d0)
- [🧪 Add number_of_clps unit tests for relation, constraints and penalties](https://github.com/glotaran/pyglotaran/commit/1f7f754f9c61968039e950cf9d4616fc442ce2f7)
- [🧪 Added number_of_clps unit test for full model](https://github.com/glotaran/pyglotaran/commit/eecd353e302e3c974ac873df40e050e53c925cc3)
- [🧹 Fix typos in error docstrings](https://github.com/glotaran/pyglotaran/commit/04e7bb2744da93cbcc9bb1b66e72a0e14a04cebb)

### Checklist

- [x] ✔️ Passing the tests (mandatory for all PR's)
- [x] 🚧 Added changes to changelog (mandatory for all PR's)
- [x] 👌 Closes issue (mandatory for ✨ feature and 🩹 bug fix PR's)
- [x] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)

### Closes issues

closes #1086

### CODE REVIEW

**Review by joernweissenborn — APPROVED** [review]
lgtm

**Review by jsnel — APPROVED** [review]
Ok, from my side. The unit tests I requested have been added, thanks.

**Review by ism200 — APPROVED** [review]
thanks a lot for this !

**Comment by ism200** [comment]
thanks a lot for this !

**Pull request merged**
