### PR TITLE
✨✨✨ Megacomplex based models, full models (spectrotemporal), damped oscillations models (DOAS), 🧪 test result validation ✔️

### LINKED ISSUE #777: Checklist for merging staging into main
Tasks:
- [x] Create a draft PR
- [x] Bring staging up to date with main
- [x] Document changes in PR

- [x] Prepare v0.5 release notes (see PR message in #778)

### PR DESCRIPTION
**Pull request by jsnel**
Megacomplex composition, spectrotempraol (full) models and fitting damped oscillations are now a thing!
This (rather massive) PR bring in some amazing changes - detailed below, consistency checking and significant speed improvements! 

This PR makes that pyglotaran can finally be called 'feature complete' and sets the stage for a v0.5.0 release.

### Major new features
- ✨ Feature: Megacomplex Models (#736)
- ✨ Feature: Full Models (#747)
- ✨ Damped Oscillation Megacomplex (a.k.a. DOAS) (#764) 
- 🧪🚇 Add integration test result validation (#754) 

### Other major changes
- 🩹 Fix Performance Regressions (#740) 
- 🩹 Fix/cli0.5 (#765)

### Minor changes:
- 🔧Add more QA tools for parts of glotaran (#739)
- 🩹Fix check_deprecations not showing deprecation warnings (#775)
- 🔧 Fix interrogate usage (#781) 
- 📚 Add docs for the CLI (#784)
- 🚇 Speedup PR benchmark (#785)
- 👌Improve ordering in k_matrix involved_compartments function (#788)
- 🩹 Fix and re-enable IRF Dispersion Test (#786)
- 🩹 Fix compartment ordering randomization due to use of set (#799) 
- 🩹 False positive model validation fail when combining multiple default megacomplexes (#797)
- 👌 Improvements to application of clp_penalties (equal area) (#801)
- ♻️ Refactor model.from_dict to parse megacomplex_type from dict and add simple_generator for testing (#807)
- 🩹 Fix coherent artifact crash for index dependent models #808

### Checklist
- [x] Complete tasks in #777 
- [x] ✔️ Passing the tests (mandatory for all PR's)
- [x] 👌 Closes issue (mandatory for ✨ feature and 🩹 bug fix PR's)
- [x] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)
- [x] 📚 Adds documentation of the feature

### Closes issues

closes #777 
(and many issues linked to in the above referenced PRs)

### CODE REVIEW

**Comment by jsnel** [comment]
It's time to merge **staging** into **main**.
This massive PR 6 months in the making is finally ready for the final review! 
 
Note to 📚 reviewers 📚: Please note that each individual PR merged into the staging branch had already been review separately, so there's no need to review this PR in its entirety.  If you find issues create a new issues for it to be picked up after merging this PR into main, before preparing the v0.5.0 release.

Note to 🚧 maintainers 🚧: This PR, because of it's size, **will be merged (by 🚧 @jsnel 🚧 !!! ) as a rebase commit**, rather than a squash and merge, in order to retain some of the historical value provided by the individual commits - and keep all the extensive commit messages.

Note to supervisor (@ism200) : This is the big one you have been waiting for.

**Review by joernweissenborn — APPROVED** [review]
LHTMB (Let's hit that merge button)

**Review by s-weigand — APPROVED** [review]
LGTM 🚀

**Comment by jsnel** [comment]
🚀  Final score ... +7,897 −5,366 😱 

Thanks for the tremendous effort @joernweissenborn and @s-weigand!

**Comment by s-weigand** [comment]
@jsnel This wouldn't have been possible without you!
So thanks and GZ @glotaran in general 😄 

[`0.5.0`](https://github.com/glotaran/pyglotaran/milestone/16) here we come 😋

**Pull request merged**
