### PR TITLE
🎨 Add new logo

### LINKED ISSUE #832: ✨ Time for a new logo
### pyglotaran needs a new logo

With the upcoming new 'major' release v0.5.0 it is time to refresh the branding. 
We have been piggy-backing on the old glotaran logo, which has been fine, but I think pyglotaran deserves its own logo, with a more modern look.

### Describe the solution you'd like

For the new logo I'd like to see a more square with rounded edges style, giving us a more modern look.
I'd like to retain the aspect of the cyclic nature in any Problem Solving Environment (PSE), e.g. the parameter estimation loop, the model adjustment loop, etc. as is currently represented by the circular arrows. But rather than 3 arrows in a circle, I suggest we use 4 going around in a square with rounded edges. 

Screenshot 2021-09-19 082358

### Requirements

The graphics should be vector-graphics (e.g. .svg) easily editable in Inkscape or another open source tool and not required proprietary or licensed software to modify.  

Main logo
- Square with rounded edges
- The square is made of rounded edges
- If aesthetics requires it the arrow head can only point inward
- Should retain the colorful design
- Should retain the GTA abbreviation, but add 'py' 
- Should still be recognizable at 32x32

High contrast logo
- Like the main logo
- Less color full
- Higher contrast (looks good when converted to monochrome)

Icon logo:
- Should still be recognizable at 16x16
- Like the main logo
- Arrows are less important
- Colors are less important

### PR DESCRIPTION
**Pull request by s-weigand**
This adds the new logo discusses in #832 with the colored border being implemented via CSS instead of a base64 encoded image.

After we finalized decisions about the logos themself (colors, etc.), I will run `docs/source/images/recreate_png_logos.py` and create the png logos with the different resolutions.

Original logo design @SerLap 
Original favicon design @jsnel 

[New logo in the docs](https://pyglotaran--1083.org.readthedocs.build/en/1083/)

### Change summary

- [✨🎨 Added new logos](https://github.com/glotaran/pyglotaran/commit/19aced73cb477930f3f4be8eaf039f602998c164)
- [✨🎨 Added new favicons based on the new logos](https://github.com/glotaran/pyglotaran/commit/a3a774711b6f3098286e6490df58ea6c4af22ebf)
- [🩹 Fixed mask alignement](https://github.com/glotaran/pyglotaran/commit/11780e361a8d784f18d2c3392f3012d3668d3cd5)
- [👌🎨 Changed used color to use nearly black and nearly white](https://github.com/glotaran/pyglotaran/commit/fc492fbf29d15beedc961bc1994aa61aa2f1eb83)
- [✨ Added script to render svg files to pgn with different sizes](https://github.com/glotaran/pyglotaran/commit/47609c06a676bc802d008af032855040c662e063)
- [📚 Changed logo and favicon in docs](https://github.com/glotaran/pyglotaran/pull/1083/commits/67ab097bb5ee645a1f35683dbccdfca75432236e)

### Checklist

- [x] ✔️ Passing the tests (mandatory for all PR's)
- [x] 🚧 Added changes to changelog (mandatory for all PR's)
- [x] 👌 Closes issue (mandatory for ✨ feature and 🩹 bug fix PR's)
- [x] 📚 Adds documentation of the feature

### Closes issues

closes #832

### CODE REVIEW

**Review by jsnel — DISMISSED** [review]

**Review by ism200 — DISMISSED** [review]
fine with me
thanks

**Review by SerLap — COMMENTED** [review]
pyGlot_black

what about such version for dark scheme

**Comment by s-weigand** [comment]
@SerLap I updated the color gradient for dark theme based on [your comment](https://github.com/glotaran/pyglotaran/pull/1083#pullrequestreview-994552473) and also changed the text and background colors to have a stronger contrast.
@jsnel and I decided to only use a text border for the transparent images since there readability is always a gamble depending on users having a light or dark theme.

**Comment by SerLap** [comment]
Looks ok to me

**Review by jsnel — APPROVED** [review]
Looks good to me too! 🚀

**Pull request merged**
