### PR TITLE
🚧 Update issue and PR templates

### PR DESCRIPTION
**Pull request by s-weigand**
Moved issue and PR templates to the proper folders and changed templates to differentiate better between different types of issues and PRs.

Ref:
[GitHub communities docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests)

**Testing**

Passing the tests is mandatory.

**Related issue**
#608

### CODE REVIEW

**Comment by s-weigand** [comment]
If you want to try it out I temporarily changed the default branch of [my fork](https://github.com/s-weigand/pyglotaran) to this branch and allowed issues. The assigning and label functionality might not work there though, since there are different labels and it isn't part of the glotaran orga.

**Comment by s-weigand** [comment]
Hmm, the issue templates work fine, but the PR templates don't... need some investigating.

**Comment by s-weigand** [comment]
Ok sadly there isn't a nice UI selector for PR templates and there is for issue templates, but it was requested multiple times:
- [Multiple Pull Request Templates](https://github.community/t/multiple-pull-request-templates/1850)
- [Is there a Pull request Template selector similar to issues?](https://github.community/t/is-there-a-pull-request-template-selector-similar-to-issues/171838)
- [Pull request template similar to issue templates](https://github.community/t/pull-request-template-similar-to-issue-templates/2389)
- [Multiple Pull Request Template](https://github.community/t/multiple-pull-request-template/874)

And was [added to the requested feature list](https://github.community/t/pull-request-template-similar-to-issue-templates/2389/4?u=s-weigand).

To use a specific PR template you need to add `?expand=1&template=<template_file_name>` to the URL of your PR.
E.g.
https://github.com/s-weigand/pyglotaran/compare/issue-PR-templates...s-weigand:depr-clean?expand=1&template=docs_PR.md

Also, It looks like the PR templates don't support the special template headers that issue templates support.

So until GitHub properly support multiple templates with easy usage we need a default template (`.github/PULL_REQUEST_TEMPLATE.md`)

The question now is, do we want to also keep custom templates and add a guide to the docs on how to use them (I at least would use them) or just delete them again?

**Comment by s-weigand** [comment]
[Custom PR template usage](https://pyglotaran--692.org.readthedocs.build/en/692/contributing.html#get-started)

And here are some test PRs with the template:
- [default template](https://github.com/s-weigand/pyglotaran/pull/65)
- [feature_PR.md](https://github.com/s-weigand/pyglotaran/pull/64)

**Review by jsnel — APPROVED** [review]
Very nice. Thanks.

**Pull request merged**
