### PR TITLE
Use a notebook for quickstart

### LINKED ISSUE #554: Quickstart as a notebook
There would be advantages to having a [quickstart](https://pyglotaran.readthedocs.io/en/latest/quickstart.html) example in a (unit testable) notebook, instead of only as part of an .rst in which (easily forgotten Python code) is executed to generate the online plots in the [pyglotaran readthedocs](https://pyglotaran.readthedocs.io/en/latest/quickstart.html)

### PR DESCRIPTION
**Pull request by s-weigand**
This PR reimplements the quickstart as a notebook and needed additional tooling.

### Advantages of using notebooks over `.*rst` files for code examples:
- Notebooks can be tested cell by cell, so errors (e.g. breaking API changes can be quickly determined and pinpointed)
- Writing the docs in notebooks one can use autocomplete and help functionality
- Using mybinder.org users can interact with the docs and have a pyglotaran [hands-on experience](https://mybinder.org/v2/gh/s-weigand/pyglotaran/quickstart-notebook?urlpath=lab/tree/docs/source/notebooks/quickstart.ipynb)
- Data (e.g. a model file) can be loaded dynamically, so there is no more need for copy pasting
- The output always corresponds to the current behavior of pyglotaran since it is always freshly generated when creation the docs
-  We can use all the autoformatting and lining tools we learned to love from normal python code

### Won't notebooks spam massive diffs as they did before?
No, we live in 2021 and the tooling has evolved quite a lot.
The main reason for notebooks to have a massive diff was plotting, since each time a plot got updated as base64 representation of the plot was saved to the notebook.
Now we have tooling in place that removes all output when committing a notebook, thus the diff is only the actual change itselfe.

**Testing**

Passing the tests is mandatory.

**Closing issues**

closes #554

### CODE REVIEW

**Review by jsnel — DISMISSED** [review]
Looks like a very comprehensive PR. The RTD page auto-generated from the notebook looks really good. Just needs the "very early stage of development" warning removed since we are now at a version useable for science (0.3.0).

**Comment by s-weigand** [comment]
> The RTD page auto-generated from the notebook looks really good. Just needs the "very early stage of development" warning removed since we are now at a version useable for science (0.3.0).

Done in https://github.com/glotaran/pyglotaran/pull/568/commits/6ceba8c0da713394cb69a55365aa12ef47d5cbe8 😄

**Review by jsnel — DISMISSED** [review]
Changed to notebook reviewed ok.

**Review by jsnel — APPROVED** [review]
LGTM

**Review by jsnel — APPROVED** [review]
Final approval

**Pull request merged**
