### PR TITLE
fix bug in irf normalization (added an "s" after irfscale)

### LINKED ISSUE #1157: 🐛 Issues with normalization of traces when fitting multiple datasets
### Version information

- pyglotaran version: main (v0.7.0-dev)
- contributor: @ism200 

### Describe the bug

In a (fairly) complex fit of multiple datasets the scaling of fitted traces appears to be incorrect, as judged by domain expert @ism200 using `timu` as reference,

Should look like this:
image
image

But looks like this instead:
image
image

### To Reproduce

(Can only be reproduced internally, internal reference: `PSI_7335_7521WLproject`)

### PR DESCRIPTION
**Pull request by ism200**
small bug fix related to normalization of datasets

### Change summary

- Changed normalization of concentration matrix if dataset_model.irf.normalize is true.

### Checklist

- [x] ✔️ Passing the tests (mandatory for all PR's)
- [x] 🚧 Added changes to changelog (mandatory for all PR's)
- [x] 👌 Closes issue (mandatory for ✨ feature and 🩹 bug fix PR's)

### Closes issues

closes #1157

### CODE REVIEW

**Review by joernweissenborn — DISMISSED** [review]
I instructed @ism200

**Comment by jsnel** [comment]
@joernweissenborn and @s-weigand, can a unit test be added by us to cover this case?

**Comment by joernweissenborn** [comment]
> @joernweissenborn and @s-weigand, can a unit test be added by us to cover this case?

Yes, when we revamp the megacomplex, so in later pr

**Comment by ism200** [comment]
@jsnel this fixes the bug in my case study with multi-gaussian irfs and multiple time ranges (streak)

**Comment by jsnel** [comment]
See comparison of results running code under this PR to reference in comment under the issue:
https://github.com/glotaran/pyglotaran/issues/1157#issuecomment-1301354987

**Review by jsnel — APPROVED** [review]
Reviewed and tested ok, see results of validation in #1157.

Note for @glotaran/maintainers, the examples than run in the CI are not affected by this change (code path not executed), so unit tests are needed, as well as an integration tests.

**Comment by jsnel** [comment]
Thank you @ism200 Ivo for contributing this bug fix and congratulations on this (first?) PR to main! 🎉

**Pull request merged**
