### PR TITLE
🧪🚇 Add integration test result validation

### LINKED ISSUE #753: 🚇Add result validation step to CI
### Describe the tooling

Right now the integration tests only show breaking API changes, but checking validity is still a manual task.
The CI should show us if the results change and we should investigate further.

### PR DESCRIPTION
**Pull request by s-weigand**
Right now the integration tests only show breaking API changes, but checking validity is still a manual task.
This PR adds a way to compare the results to a "gold standard" (tag, branch, commit) set by [this workflow](https://github.com/glotaran/pyglotaran-examples/actions/workflows/update_compare_results.yml) on the `pyglotaran-examples` repo.

### Change summary

- Adds numerical comparison to "gold standard" results defined by `pyglotaran-examples`

### Checklist

- [x] ✔️ Passing the tests (mandatory for all PR's)
- [x] 🧪 Adds new tests for the feature (mandatory for ✨ feature and 🩹 bug fix PR's)

### Closes issues

closes #753

### CODE REVIEW

**Comment by s-weigand** [comment]
For this workflow to pass we might need to fix how `problem.save_parameters_for_history` is implemented in `optimize` and make a fix release `0.4.1`, since it is done wrong according to @joernweissenborn 🤷‍♀️.
At least we now have a way to compare the results across versions.

**Review by jsnel — APPROVED** [review]
LGTM

**Comment by s-weigand** [comment]
The `clp_label` swapping for `ex_two_datasets` in [this CI run](https://github.com/glotaran/pyglotaran/runs/3329625935?check_suite_focus=true)
might be related to the implementation of `involved_compartments` 
https://github.com/glotaran/pyglotaran/blob/d2b297b534dd7092eb3c00d69132da7c0e4971ee/glotaran/builtin/megacomplexes/decay/k_matrix.py#L47

Since set **does not** preserve order.

Using `frozenset` might solve this, or even better using the user-provided order from the defined model (not sure if we still have access to that on this point).

**Comment by s-weigand** [comment]
@jsnel  and I did a long debugging session today where we found the following:
- weights are applied differently (compartment order) between `0.4.1` and `staging` (failing `ex_two_datasets` and possibly `simultaneous_analysis_6d_disp`)
- the missing coordinate `spectral` is due to different code paths when auto determining index dependency `UngroupedProblem.create_index_dependent_result_dataset` vs. `UngroupedProblem.create_index_independent_result_dataset` (also this is kinda random or maybe I messed the tests up [Missing coordinate: 'spectral' in 'dataset1.nc', data_var 'matrix'](https://github.com/glotaran/pyglotaran/runs/3334331574?check_suite_focus=true) vs. [`spectral` is apparently present](https://github.com/glotaran/pyglotaran/pull/754/checks?check_run_id=3335789476))
- problems in `simultaneous_analysis_6d_disp` might be due to missing noise and/or the differences in how weights are applied

**Pull request merged**
